import { RuleDefinition } from '../types';

export const RULES: Record<string, RuleDefinition> = {
  // Category 1: Secrets & Credentials
  'hardcoded-secret': {
    id: 'hardcoded-secret',
    category: 'secrets',
    title: 'Hardcoded Secret or API Key',
    defaultSeverity: 'critical',
    baseDeduction: 15,
    description: 'Hardcoded secret, API token, password, or high-entropy credential found in source code.',
    fix: 'Move secret into an environment variable and load it via process.env.',
  },
  'direct-env-access': {
    id: 'direct-env-access',
    category: 'secrets',
    title: 'Improper .env Value Reference',
    defaultSeverity: 'high',
    baseDeduction: 8,
    description: 'Referencing .env files or bare env globals directly instead of standard process.env.',
    fix: 'Use process.env.VARIABLE_NAME or load validated environment variables through a config module.',
  },
  'uncommitted-env-secret': {
    id: 'uncommitted-env-secret',
    category: 'secrets',
    title: 'Committed .env File Containing Secrets',
    defaultSeverity: 'critical',
    baseDeduction: 20,
    description: '.env file containing potential real secrets or API keys is not ignored in .gitignore.',
    fix: 'Add .env (and .env.*.local) to .gitignore and use .env.example with dummy values instead.',
  },

  // Category 2: Auth & Access Control
  'no-auth-middleware': {
    id: 'no-auth-middleware',
    category: 'auth',
    title: 'Route Handler Missing Auth Middleware',
    defaultSeverity: 'high',
    baseDeduction: 10,
    description: 'Express or Next.js route handler detected without authentication middleware or session check.',
    fix: 'Add auth middleware (e.g., requireAuth, passport.authenticate, or getServerSession).',
  },
  'unprotected-sensitive-route': {
    id: 'unprotected-sensitive-route',
    category: 'auth',
    title: 'Sensitive Route Missing Auth Guard',
    defaultSeverity: 'critical',
    baseDeduction: 15,
    description: 'Endpoint path indicates sensitive operations (/user, /admin, /billing, /payment) without auth guard.',
    fix: 'Enforce authentication and session validation before processing sensitive user/billing data.',
  },
  'missing-role-check': {
    id: 'missing-role-check',
    category: 'auth',
    title: 'Missing Role or Permission Check',
    defaultSeverity: 'high',
    baseDeduction: 10,
    description: 'Privileged route or admin action performs mutations without role or permission checks.',
    fix: 'Verify user roles (e.g., req.user.role === "admin" or checkPermission("admin")) before executing.',
  },

  // Category 3: Input Validation
  'unvalidated-request-input': {
    id: 'unvalidated-request-input',
    category: 'validation',
    title: 'Unvalidated Request Input',
    defaultSeverity: 'high',
    baseDeduction: 8,
    description: 'Route accesses req.body, req.query, or req.params without schema validation (zod, joi, yup).',
    fix: 'Parse and validate request data using a validation library such as Zod, Joi, or Yup.',
  },
  'raw-sql-injection': {
    id: 'raw-sql-injection',
    category: 'validation',
    title: 'Raw SQL String Concatenation (SQLi Risk)',
    defaultSeverity: 'critical',
    baseDeduction: 15,
    description: 'Dynamic SQL query constructed with string concatenation or unparameterized template literals.',
    fix: 'Use parameterized queries, prepared statements ($1, ?), or an ORM/query builder (Prisma, Drizzle).',
  },
  'unsafe-input-execution': {
    id: 'unsafe-input-execution',
    category: 'validation',
    title: 'Dangerous Code Execution / Injection',
    defaultSeverity: 'critical',
    baseDeduction: 15,
    description: 'Potentially unsanitized input passed to eval, exec, child_process, or dangerouslySetInnerHTML.',
    fix: 'Avoid eval/exec; sanitize HTML using DOMPurify before setting dangerouslySetInnerHTML.',
  },

  // Category 4: Error Handling
  'unhandled-async-route': {
    id: 'unhandled-async-route',
    category: 'errorHandling',
    title: 'Async Route Without Error Boundary',
    defaultSeverity: 'medium',
    baseDeduction: 6,
    description: 'Async Express or API route handler lacks try/catch or async-handler wrapper, risking server crashes.',
    fix: 'Wrap handler logic in try/catch or wrap the route with express-async-handler.',
  },
  'unhandled-promise': {
    id: 'unhandled-promise',
    category: 'errorHandling',
    title: 'Unhandled Promise Rejection Risk',
    defaultSeverity: 'medium',
    baseDeduction: 5,
    description: 'Promise invocation without await, return, or .catch() handler.',
    fix: 'Await the promise inside a try/catch block or attach a .catch() handler.',
  },
  'empty-catch-block': {
    id: 'empty-catch-block',
    category: 'errorHandling',
    title: 'Swallowed Error in Empty Catch Block',
    defaultSeverity: 'medium',
    baseDeduction: 5,
    description: 'Catch block is completely empty or swallows errors without logging or re-throwing.',
    fix: 'Log the error with logger.error(err) or handle/rethrow appropriately.',
  },

  // Category 5: Testing
  'untested-source-file': {
    id: 'untested-source-file',
    category: 'testing',
    title: 'Source File Has No Matching Test',
    defaultSeverity: 'medium',
    baseDeduction: 4,
    description: 'Core source file has no corresponding test file in the test directory or alongside source.',
    fix: 'Add a unit test file (e.g. filename.test.ts) covering the critical exports of this module.',
  },
  'stub-test-file': {
    id: 'stub-test-file',
    category: 'testing',
    title: 'Stub Test File With Zero Assertions',
    defaultSeverity: 'high',
    baseDeduction: 6,
    description: 'Test file contains test suites or test cases with 0 assertions or empty test blocks.',
    fix: 'Add concrete expect() or assert statements verifying actual behavior.',
  },
  'low-test-ratio': {
    id: 'low-test-ratio',
    category: 'testing',
    title: 'Low Test-to-Source File Ratio',
    defaultSeverity: 'medium',
    baseDeduction: 6,
    description: 'Test file count is significantly lower than source files (< 30% coverage ratio).',
    fix: 'Increase test coverage by adding integration and unit tests for untested business logic.',
  },

  // Category 6: Reliability / Config Hygiene
  'console-log-in-production': {
    id: 'console-log-in-production',
    category: 'reliability',
    title: 'console.log in Production Code',
    defaultSeverity: 'low',
    baseDeduction: 2,
    description: 'console.log left in application routes or production logic rather than a structured logger.',
    fix: 'Replace console.log with a structured logger (pino, winston) or remove debug logs.',
  },
  'missing-rate-limiting': {
    id: 'missing-rate-limiting',
    category: 'reliability',
    title: 'Missing API Rate Limiting',
    defaultSeverity: 'medium',
    baseDeduction: 5,
    description: 'Express or API server has public endpoints but no rate limiting middleware configured.',
    fix: 'Add express-rate-limit or an edge rate limiter to prevent brute force and denial-of-service.',
  },
  'cors-wildcard': {
    id: 'cors-wildcard',
    category: 'reliability',
    title: 'CORS Configured with Wildcard (*)',
    defaultSeverity: 'medium',
    baseDeduction: 4,
    description: 'CORS configured to allow all origins (*) in production application.',
    fix: 'Restrict CORS origin to specific trusted frontend domains.',
  },
  'missing-security-headers': {
    id: 'missing-security-headers',
    category: 'reliability',
    title: 'Missing Security Headers (Helmet)',
    defaultSeverity: 'medium',
    baseDeduction: 5,
    description: 'Express server does not use helmet or set standard security headers (CSP, HSTS, X-Frame-Options).',
    fix: 'Install and use helmet (app.use(helmet())) to secure HTTP response headers.',
  },
};
